@IPB2.HW.RestaurantOrderManagementSystem.MinimalApiApp_HostAddress = http://localhost:5057

GET {{IPB2.HW.RestaurantOrderManagementSystem.MinimalApiApp_HostAddress}}/weatherforecast/
Accept: application/json

###
